services:
  gstr:
    container_name: gstr
    build: .
    volumes:
      - ./gstr/:/app/gstr/gstr/
      - ./static/:/app/gstr/static/
      - ./scripts/:/app/gstr/scripts/
    entrypoint: ["tail", "-f", "/dev/null"]

  mediamtx:
    container_name: mediamtx
    image: bluenviron/mediamtx:latest
    environment:
      - MTX_PROTOCOLS=tcp
      - MTX_WEBRTCADDITIONALHOSTS=0.0.0.0
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890/udp"
      - "8189:8189/udp"
